name: deep
channels:
  - defaults
dependencies:
  - python=3.6.8
  - pip=19.2.2
  - pip:
      - ipykernel==5.1.2
      - jupyter==1.0.0
      - tensorflow==2.6.0
      - matplotlib==3.3.4
      - pandas==1.1.5
      - scikit-learn==0.24.2
